# Generated by Django 3.2 on 2021-04-26 15:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pytania', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lekcja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa', models.CharField(max_length=1024)),
            ],
        ),
        migrations.AddField(
            model_name='pytanie',
            name='lekcja',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='pytania.lekcja'),
            preserve_default=False,
        ),
    ]
